version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp/api
    container_name: $APP_NAME
    networks:
      - $APP_NETWORK
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - /app/node_modules
      - .:/app
    command: ['yarn', 'dev']
    external_links:
      - postgres:postgres
      - adminer:adminer

networks:
  main:
    external: true
