version: '3.7'

services:
  server:
    build:
      context: .
    container_name: server
    networks:
      - $APP_NETWORK
    working_dir: /app
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/app
    command: 'yarn dev'
    depends_on:
      - postgres
    external_links:
      - postgres:postgres
      - adminer:adminer
    restart: 'unless-stopped'

networks:
  main:
    external: true
