# baseURL
@baseURL = http://localhost:3000

###
# Find All categories
GET {{ baseURL }}/categories

###
# Find Category By Id
GET {{ baseURL }}/categories/123e4567-e89b-12d3-a456-426614174000

###
# Create Category
POST {{ baseURL }}/categories
Content-Type: application/json

{
  "name": "music",
}

###
# Modify Category By Id
PUT {{ baseURL }}/categories/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "music",
}

###
# Delete Category By Id
DELETE {{ baseURL }}/categories/123e4567-e89b-12d3-a456-426614174000
